blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/turboforge-dev/turboforge/discussions
    about: Ask questions and share ideas with the community.
  # - name: 📖 Documentation
  #   url: https://turboforge...
  #   about: Read the official documentation.
