#!/bin/bash
REMOTE_URL=$(git remote get-url --push origin)

if [ "$REMOTE_URL" = "https://github.com/react18-tools/turbo-forge.git" ]; then
  TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  COMMIT_HASH=$(git rev-parse HEAD)
  echo "{
    \"lastSyncedCommit\": \"$COMMIT_HASH\",
    \"generatedAt\": \"$TIMESTAMP\"
  }" > .forge-meta.json
fi
