#!/bin/sh

# Check if the lockfile changed between the previous and current state
if git diff --name-only ORIG_HEAD HEAD | grep -q "pnpm-lock.yaml"; then
  echo "📦 Lockfile change detected. Running pnpm install..."
  pnpm install --frozen-lockfile
fi
